/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SoilParameters = IDL.Record({
  'pH' : IDL.Float64,
  'chromiumPPM' : IDL.Float64,
  'leadPPM' : IDL.Float64,
  'phosphorusPPM' : IDL.Float64,
  'zincPPM' : IDL.Float64,
  'nickelPPM' : IDL.Float64,
  'organicMatterPercentage' : IDL.Float64,
  'arsenicPPM' : IDL.Float64,
  'nitrogenPPM' : IDL.Float64,
  'cadmiumPPM' : IDL.Float64,
});
export const SoilAnalysisRecord = IDL.Record({
  'id' : IDL.Nat,
  'remediationCycles' : IDL.Int,
  'owner' : IDL.Principal,
  'parameters' : SoilParameters,
  'recommendedPlant' : IDL.Text,
  'confidenceScore' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSoilAnalysisRecord' : IDL.Func(
      [SoilParameters, IDL.Text, IDL.Int, IDL.Float64, IDL.Principal],
      [SoilAnalysisRecord],
      [],
    ),
  'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(SoilAnalysisRecord)], ['query']),
  'getAnalysis' : IDL.Func([IDL.Nat], [SoilAnalysisRecord], ['query']),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(SoilAnalysisRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecordCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAnalysis' : IDL.Func(
      [SoilParameters, IDL.Text, IDL.Int, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SoilParameters = IDL.Record({
    'pH' : IDL.Float64,
    'chromiumPPM' : IDL.Float64,
    'leadPPM' : IDL.Float64,
    'phosphorusPPM' : IDL.Float64,
    'zincPPM' : IDL.Float64,
    'nickelPPM' : IDL.Float64,
    'organicMatterPercentage' : IDL.Float64,
    'arsenicPPM' : IDL.Float64,
    'nitrogenPPM' : IDL.Float64,
    'cadmiumPPM' : IDL.Float64,
  });
  const SoilAnalysisRecord = IDL.Record({
    'id' : IDL.Nat,
    'remediationCycles' : IDL.Int,
    'owner' : IDL.Principal,
    'parameters' : SoilParameters,
    'recommendedPlant' : IDL.Text,
    'confidenceScore' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSoilAnalysisRecord' : IDL.Func(
        [SoilParameters, IDL.Text, IDL.Int, IDL.Float64, IDL.Principal],
        [SoilAnalysisRecord],
        [],
      ),
    'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(SoilAnalysisRecord)], ['query']),
    'getAnalysis' : IDL.Func([IDL.Nat], [SoilAnalysisRecord], ['query']),
    'getAnalysisHistory' : IDL.Func(
        [],
        [IDL.Vec(SoilAnalysisRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecordCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAnalysis' : IDL.Func(
        [SoilParameters, IDL.Text, IDL.Int, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };